"""Verify dense/sol reproducibility on 10 previously untested prompts (5 fresh + 5 remapped).

Sept-13's reuse_10pct_dense_sol.json splits the 50 prompts into 25 freshly
generated on Sept-13 (claimed reproducible) and 25 remapped from the Sept-1
10pct run (claimed unreproducible). Cases 1-10 already verified 5+5; this run
extends coverage with fresh cases 13,20,28,36,50 and remapped cases
14,17,25,33,49. Protocol is identical to dense_sol_repro_10prompt_20260920:
dense on GPUs 0-3 without plugin, sol on GPUs 4-7 with the Sept-13 isolated_run
h3_sparse_attention H3SparseAttentionConfig.sol(20); one excluded
full-generation warmup per worker; synchronized denoising only.
Expectation: fresh cases tensor-equal, remapped cases divergent, for both arms.
"""
import contextlib
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import shutil
import statistics
import subprocess
import sys
import time

REPO = Path(__file__).resolve().parents[1]
SEPT13 = Path('/autodl-fs/data/h3_experiments/vbench20pct_768p10s_seed42_20260913')
ISO = SEPT13 / 'isolated_run'
HIST_OUT = Path('/autodl-fs/data/h3_outputs/vbench20pct_768p10s_seed42_20260913')
ROOT = Path('/autodl-fs/data/h3_experiments/dense_sol_verify_extend_20260920')
OUT = Path('/autodl-fs/data/h3_outputs') / ROOT.name
SAMPLES = ISO / 'vbench_core5_percent_subsets/20pct/samples.json'
FRESH = [13, 20, 28, 36, 50]
STALE = [14, 17, 25, 33, 49]
CASES = sorted(FRESH + STALE)
SHARDS = [[13, 25, 49], [14, 28, 50], [17, 33], [20, 36]]
ENV = dict(HF_HUB_OFFLINE='1', OMP_NUM_THREADS='4', TORCHINDUCTOR_COMPILE_THREADS='4',
           PYTHONUNBUFFERED='1', PYTHONDONTWRITEBYTECODE='1', FLASHINFER_CUDA_ARCH_LIST='12.0')


def read(path):
    return json.loads(Path(path).read_text())


def write(path, obj):
    path = Path(path); path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(f'.tmp-{os.getpid()}.json')
    tmp.write_text(json.dumps(obj, indent=2) + '\n'); tmp.replace(path)


def sha(path):
    h = hashlib.sha256()
    with Path(path).open('rb') as f:
        for block in iter(lambda: f.read(8 << 20), b''): h.update(block)
    return h.hexdigest()


def prepare():
    assert not ROOT.exists(), ROOT
    ROOT.mkdir(parents=True)
    OUT.mkdir()
    for name in ('conditioning_cache', 'conditioning_manifest.json'):
        (OUT / name).symlink_to(HIST_OUT / name, target_is_directory=name == 'conditioning_cache')
    hist = {}
    for method in ('dense', 'sol'):
        recs = {read(f)['index']: read(f) for f in (HIST_OUT / method / 'denoise_records').glob('*.json')}
        for c in CASES:
            rec = recs[c]
            assert sha(rec['latent_path']) == rec['latent_sha256']
            hist[f'{method}_{c:02}'] = dict(latent_path=rec['latent_path'],
                latent_sha256=rec['latent_sha256'], historical_denoise_seconds=rec['denoise_seconds'])
    write(ROOT / 'historical_latents.json', hist)
    shutil.copy2(__file__, ROOT / 'runner_source.py')
    write(ROOT / 'protocol.json', dict(cases=CASES, fresh_cases=FRESH, remapped_cases=STALE,
        seed=42, steps=20, frames=240, fps=24, height=768, width=1344,
        gpus=dict(dense=[0, 1, 2, 3], sol=[4, 5, 6, 7]), shards=SHARDS,
        sol_code=str(ISO / 'h3_sparse_attention'),
        sol_config='Sept-13 H3SparseAttentionConfig.sol(20), field-for-field equal to the Sept-13 denoise_records attention_config.',
        timing='Synchronized denoising only; one excluded full-generation warmup per worker (its first shard prompt). torch.compile and compile_deterministic on, matching the Sept-13 run and the dense_sol_repro_10prompt_20260920 protocol.',
        expectation='Fresh cases (13,20,28,36,50, generated by the Sept-13 snapshot) must be tensor-equal for both arms; remapped cases (14,17,25,33,49, from the unsnapshotted Sept-1 run) must diverge for both arms. The provenance conclusion holds only if both predictions match.',
        environment=ENV))
    print('PREPARE OK', flush=True)


def worker(gpu):
    import torch
    torch.set_num_threads(4)
    method = 'dense' if gpu < 4 else 'sol'
    slot = gpu % 4
    my_cases = SHARDS[slot]
    spec = importlib.util.spec_from_file_location('pipeline', ISO / 'scripts/minimax_h3_vbench_4gpu_pipeline.py')
    p = importlib.util.module_from_spec(spec)
    sys.modules['pipeline'] = p
    spec.loader.exec_module(p)  # self-inserts ISO and ISO/exps into sys.path
    cfg = None
    if method == 'sol':
        import h3_sparse_attention as h3old
        assert str(ISO) in h3old.__file__, h3old.__file__
        cfg = h3old.H3SparseAttentionConfig.sol(20)
    args = p.build_parser().parse_args(['denoise', '--samples', str(SAMPLES),
        '--output', str(OUT), '--method', method, '--case-indices', *map(str, my_cases),
        '--frames', '240', '--height', '768', '--width', '1344', '--steps', '20', '--workers', '1'])
    cases = p.load_cases(SAMPLES, my_cases)
    write(ROOT / f'status_gpu{gpu}.json', dict(stage='loading', method=method))
    workflow, states = p.configure_denoise_workflow(args, cases)
    pipe, manager, acceleration, placement = p.load_denoiser(args, workflow)
    try:
        for i in range(-1, len(my_cases)):
            case, state = cases[max(i, 0)], states[max(i, 0)]
            target = ROOT / 'records' / f'{method}_{case["index"]:02}.json'
            if i >= 0 and target.exists():
                continue
            prepared = p.clone_state(state)
            prepared.values['prompt_embeds'] = prepared.values['prompt_embeds'].cuda()
            write(ROOT / f'status_gpu{gpu}.json', dict(stage='warmup' if i < 0 else 'measuring',
                method=method, case=case['index']))
            if method == 'sol':
                import h3_sparse_attention as h3old
                ctx = h3old.install_h3_sparse_attention(pipe.transformer, cfg)
            else:
                ctx = contextlib.nullcontext()
            with ctx:
                torch.cuda.synchronize()
                started = time.perf_counter()
                with torch.no_grad():
                    result = pipe(state=prepared, num_frames=240, height=768, width=1344,
                        num_inference_steps=20, generator=torch.Generator(device='cpu').manual_seed(42),
                        output=['latents', 'audio_latents'])
                torch.cuda.synchronize()
                seconds = time.perf_counter() - started
            if i < 0:
                write(ROOT / f'warmup_{method}_gpu{gpu}.json', dict(seconds=seconds, case=case['index']))
            else:
                payload = {k: result[k].detach().cpu().contiguous() for k in ('latents', 'audio_latents')}
                assert all(torch.isfinite(v).all() for v in payload.values())
                path = OUT / 'latents' / f'{method}_{case["index"]:02}.pt'
                path.parent.mkdir(exist_ok=True)
                p.atomic_torch_save(payload, path)
                write(target, dict(method=method, case=case['index'], sample_id=case['sample_id'],
                    gpu=gpu, denoise_seconds=seconds, latent_path=str(path), latent_sha256=sha(path),
                    seed=42, steps=20, requested_frames=240, height=768, width=1344))
                del payload
            print(method, case['index'], 'warmup' if i < 0 else 'measured', seconds, flush=True)
            del result, prepared
        write(ROOT / f'status_gpu{gpu}.json', dict(stage='complete', method=method))
    finally:
        acceleration.remove()


def compare():
    import torch
    hist = read(ROOT / 'historical_latents.json')
    rows = []
    for method in ('dense', 'sol'):
        for c in CASES:
            new = read(ROOT / 'records' / f'{method}_{c:02}.json')
            old = hist[f'{method}_{c:02}']
            row = dict(method=method, case=c, group='fresh' if c in FRESH else 'remapped',
                denoise_seconds=new['denoise_seconds'],
                historical_denoise_seconds=old['historical_denoise_seconds'],
                historical_latent_sha256=old['latent_sha256'], new_latent_sha256=new['latent_sha256'],
                sha_equal=new['latent_sha256'] == old['latent_sha256'])
            if not row['sha_equal']:
                a = torch.load(new['latent_path'], map_location='cpu', weights_only=False)
                b = torch.load(old['latent_path'], map_location='cpu', weights_only=False)
                for k in ('latents', 'audio_latents'):
                    row[f'{k}_equal'] = bool(torch.equal(a[k], b[k]))
                    row[f'{k}_max_abs_diff'] = float((a[k] - b[k]).abs().max())
                row['latents_cosine'] = float(torch.nn.functional.cosine_similarity(
                    a['latents'].flatten().double(), b['latents'].flatten().double(), dim=0))
            rows.append(row)
    write(ROOT / 'consistency.json', dict(rows=rows))
    return rows


def aggregate():
    rows = read(ROOT / 'consistency.json')['rows']
    summary = {}
    for method in ('dense', 'sol'):
        for group in ('fresh', 'remapped'):
            mr = [r for r in rows if r['method'] == method and r['group'] == group]
            summary[f'{method}_{group}'] = dict(
                cases=[r['case'] for r in mr],
                mean_seconds=statistics.mean(r['denoise_seconds'] for r in mr),
                tensor_equal=sum(r.get('latents_equal', r['sha_equal']) for r in mr),
                max_abs_diff=max((r.get('latents_max_abs_diff', 0.0) for r in mr), default=0.0),
                min_cosine=min((r.get('latents_cosine', 1.0) for r in mr), default=1.0))
    verdict = all(summary[f'{m}_fresh']['tensor_equal'] == 5 for m in ('dense', 'sol')) \
        and all(summary[f'{m}_remapped']['tensor_equal'] == 0 for m in ('dense', 'sol'))
    write(ROOT / 'results.json', dict(status='complete', verdict='confirmed' if verdict else 'VIOLATED',
        summary=summary, rows=rows))
    lines = ['# Dense/sol reproducibility verification on 10 previously untested prompts', '',
        'Fresh Sept-13 cases 13,20,28,36,50 and remapped Sept-1 cases 14,17,25,33,49; seed 42; 1344x768; 240 frames at 24 fps; 20 requested steps. Protocol identical to dense_sol_repro_10prompt_20260920 (one excluded warmup per worker, synchronized denoising only, compile on).', '',
        '| Arm | Group | Cases | Tensor equal | Max abs diff | Min cosine | Mean seconds |',
        '|---|---|---|---:|---:|---:|---:|']
    for method in ('dense', 'sol'):
        for group in ('fresh', 'remapped'):
            s = summary[f'{method}_{group}']
            lines.append(f"| {method} | {group} | {s['cases']} | {s['tensor_equal']}/5 | {s['max_abs_diff']:.3e} | {s['min_cosine']:.6f} | {s['mean_seconds']:.3f} |")
    lines += ['', f"Verdict: {'CONFIRMED - provenance conclusion holds' if verdict else 'VIOLATED - provenance conclusion does NOT hold, investigate before any replacement'}."]
    (ROOT / 'REPORT.md').write_text('\n'.join(lines) + '\n')
    report = REPO / 'reports' / ROOT.name
    report.mkdir(parents=True, exist_ok=True)
    for name in ('results.json', 'REPORT.md', 'protocol.json', 'consistency.json'):
        shutil.copy2(ROOT / name, report / name)
    print('AGGREGATE DONE', json.dumps(dict(verdict=verdict, summary=summary), indent=1), flush=True)


def run():
    jobs = []
    for gpu in range(8):
        log = (ROOT / f'gpu{gpu}.log').open('a')
        proc = subprocess.Popen([sys.executable, __file__, 'worker', str(gpu)],
            env={**os.environ, **ENV, 'CUDA_VISIBLE_DEVICES': str(gpu)}, stdout=log, stderr=subprocess.STDOUT)
        jobs.append((proc, log))
    write(ROOT / 'pids.json', [p.pid for p, _ in jobs])
    codes = [p.wait() for p, _ in jobs]
    for _, log in jobs:
        log.close()
    write(ROOT / 'exit_codes.json', codes)
    assert not any(codes), codes
    compare()
    aggregate()


if __name__ == '__main__':
    os.environ.update(ENV)
    if sys.argv[1] == 'worker':
        worker(int(sys.argv[2]))
    else:
        globals()[sys.argv[1]]()
